### ISSUE TITLE
Report bug of newTweet api

### ISSUE THREAD

**Issue by YeechingTiger** [c78867886/TwitterBaby#53]
Return code 405 (Method not allowed).

**Comment by c78867886** [comment]
Corrected. Try the new curl:

curl -X POST http://127.0.0.1:1323/api/v1/newTweet/59d24577311bc337bfec6cf9 -H 'Content-Type: application/json' -H 'Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1MDcxNTU1MDMsImlkIjoiNTlkMTNmMDUzMTFiYzMwM2Q4NTA4MTFjIiwidXNlcm5hbWUiOiJKYXNvbkhvIn0.uiutwoG6Hdn3EQIY4fH-KMSD95Q5HM7QVOgirxcB9dY' -d '{"message":"BBBBBBBBQ"}'

And use POST method rather than GET method in front-end. Thank you!
